# Generated by Django 4.1 on 2023-05-07 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookcategory',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
