# Generated by Django 4.1 on 2023-05-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_alter_bookcategory_options_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
