# Generated by Django 4.1 on 2023-05-09 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("books", "0004_alter_book_slug"),
    ]

    operations = [
        migrations.AddField(
            model_name="bookcategory",
            name="book_count",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
